# Generated by Django 5.1.1 on 2024-10-08 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarritoApp', '0003_cliente_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='producto',
        ),
        migrations.AddField(
            model_name='orden',
            name='productos',
            field=models.ManyToManyField(to='CarritoApp.producto'),
        ),
    ]
